---
- get_route_to:
    _name: route to r1
    _kwargs:
      destination: "2001:db8:b33f::1"
      protocol: "bgp"
    2001:db8:b33f::1/128:
      list:
        - next_hop: "2001:db8:caf3:12::"
        - next_hop: "2001:db8:caf3:23::1"

- get_route_to:
    _name: route to r3
    _kwargs:
      destination: "2001:db8:b33f::3"
      protocol: "bgp"
    2001:db8:b33f::3/128:
      list:
        - next_hop: "2001:db8:caf3:12::"
        - next_hop: "2001:db8:caf3:23::1"
