---
- pause:
    seconds: 10
- block:
  - name: "validate deployment"
    napalm_validate:
      hostname: "{{ host }}"
      username: "{{ username }}"
      dev_os: "{{ os }}"
      password: "{{ password }}"
      optional_args:
        port: "{{ port }}"
      validation_file: "{{ role_path }}/files/{{ inventory_hostname }}/{{ item }}.yaml"
    register: report
    tags: [print_action]
    with_items: ["interfaces", "bgp", "routes"]
  rescue:
    - name: "Report"
      debug:
        msg: "{{ report|to_nice_json }}"
      tags: [print_action]
