---
- get_bgp_neighbors:
    global:
      router_id: 3.3.3.3
      peers:
        _mode: strict
        2001:db8:caf3:13:::
          is_up: yes
          address_family:
            ipv6:
              received_prefixes: '>0'
              sent_prefixes: '>0'
        2001:db8:caf3:23:::
          is_up: yes
          address_family:
            ipv6:
              received_prefixes: '>0'
              sent_prefixes: '>0'
