---
- get_interfaces_ip:
    ge-0/0/1.0:
      ipv6:
        2001:db8:caf3:13::1:
          prefix_length: 127
    ge-0/0/2.0:
      ipv6:
        2001:db8:caf3:23::1:
          prefix_length: 127
    lo0.0:
      ipv6:
        2001:db8:b33f::3:
          prefix_length: 128

- get_bgp_neighbors:
    global:
      router_id: 3.3.3.3
      peers:
        _mode: strict
        2001:db8:caf3:13:::
          is_up: yes
          address_family:
            ipv6:
              received_prefixes: '>0'
              sent_prefixes: '>0'
        2001:db8:caf3:23:::
          is_up: yes
          address_family:
            ipv6:
              received_prefixes: '>0'
              sent_prefixes: '>0'

- get_route_to:
    _name: route to r1
    _kwargs:
      destination: "2001:db8:b33f::1"
      protocol: "bgp"
    2001:db8:b33f::1/128:
      list:
        - next_hop: "2001:db8:caf3:13::"
        - next_hop: "2001:db8:caf3:23::"

- get_route_to:
    _name: route to r2
    _kwargs:
      destination: "2001:db8:b33f::2"
      protocol: "bgp"
    2001:db8:b33f::2/128:
      list:
        - next_hop: "2001:db8:caf3:13::"
        - next_hop: "2001:db8:caf3:23::"
